import Head from "next/head";

import {
  persistStore,
  persistReducer,
  FLUSH,
  REHYDRATE,
  PAUSE,
  PERSIST,
  PURGE,
  REGISTER,
} from "redux-persist";
import storage from "redux-persist/lib/storage";
import { PersistGate } from "redux-persist/integration/react";
import authReducer from "../redux/index";
import { configureStore } from "@reduxjs/toolkit";
import { Provider } from "react-redux";
import Navbar from "@/components/Navbar";
import Input_Photo from "@/components/Homepage_components/Input_Photo";
import Add_Video from "@/components/Homepage_components/Add_Video";
import PostBox from "@/components/Homepage_components/PostBox";
import PostCard from "@/components/Homepage_components/PostCard";

const persistConfig = { key: "root", storage, version: 1 };
const persistedReducer = persistReducer(persistConfig, authReducer);
const store = configureStore({
  reducer: persistedReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
      },
    }),
});

const dummyData = [
  {
    id: 2,
    username: "Farhat Mahi",
    time_posted: "1d ago",
    profile_picture:
      "https://images.unsplash.com/photo-1595152452543-e5fc28ebc2b8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWVuJTIwcG9ydHJhaXR8ZW58MHx8MHx8&w=1000&q=80",
    image:
      "https://images.pexels.com/photos/307008/pexels-photo-307008.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 3,
    username: "Jhankar Mahbub",
    time_posted: "2d ago",
    profile_picture:
      "https://static1.squarespace.com/static/59dce1fa80bd5e67177b5efe/t/59e8d54eedaed82b728ea70d/1508431323095/11138647_10152658520856891_2718987297397745986_n.jpg?format=1000w",
    image: "https://m.media-amazon.com/images/I/51CsDxe7mKL.jpg",
  },
];

export default function Home() {
  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        {/* page header  */}
        <div className="flex justify-between items-center py-4">
          <h1 className="text-2xl font-bold">Home</h1>
          <button className="btn btn-outline border-secondary text-black rounded-full hover:border-black hover:text-black hover:bg-transparent text-sm font-extralight">
            All
          </button>
        </div>
        {/* post box  */}
        <PostBox />
        {dummyData.map((data) => (
          <PostCard key={data.id} data={data} />
        ))}
      </div>
    </Provider>
  );
}
