import Head from "next/head";
import authReducer from "../redux/index";
import { configureStore, getDefaultMiddleware } from "@reduxjs/toolkit";
import { Provider } from "react-redux";
import {
  persistStore,
  persistReducer,
  FLUSH,
  REHYDRATE,
  PAUSE,
  PURGE,
  REGISTER,
} from "redux-persist";
import storage from "redux-persist/lib/storage";
import { PersistGate } from "redux-persist/integration/react";

const persistConfig = { key: "root", storage, version: 1 };
const persistedReducer = persistReducer(persistConfig, authReducer);
const store = configureStore({
  reducer : persistedReducer, 
  middleware : (getDefaultMiddleware) => {
    getDefaultMiddleware({
      serializableCheck : {
        ignoreActions : [FLUSH, REGISTER, REHYDRATE, PURGE, PAUSE]
      }
    })
  }
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Social Media App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
